#------------------------------------------------------------------------------
# yazi Color Theme File
#------------------------------------------------------------------------------

# ln -s $HOME/personal/dotfiles/yazi/theme.toml $HOME/.config/yazi/theme.toml
