---

# -----------------------------------------------------------------------------
# Lazygit Configuration File
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
# -----------------------------------------------------------------------------

gui:
  # The number of lines you scroll by when scrolling the main window
  scrollHeight: 3

  # If true, allow scrolling past the bottom of the content in the main window
  scrollPastBottom: true

  # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#scroll-off-margin
  scrollOffMargin: 2

  # One of: 'margin' (default) | 'jump'
  scrollOffBehavior: margin

  # If true, capture mouse events.
  # When mouse events are captured, it's a little harder to select text: e.g. requiring you to hold the option key when on macOS.
  mouseEvents: true

  # If true, do not show a warning when discarding changes in the staging view.
  skipDiscardChangeWarning: false

  # If true, do not show warning when applying/popping the stash
  skipStashWarning: false

  # If true, do not show a warning when attempting to commit without any staged files; instead stage all unstaged files.
  skipNoStagedFilesWarning: false

  # If true, do not show a warning when rewording a commit via an external editor
  skipRewordInEditorWarning: false

  # Fraction of the total screen width to use for the left side section. You may want to pick a small number (e.g. 0.2) if you're using a narrow screen, so that you can see more of the main section.
  # Number from 0 to 1.0.
  sidePanelWidth: 0.3333

  # If true, increase the height of the focused side window; creating an accordion effect.
  expandFocusedSidePanel: false

  # The weight of the expanded side panel, relative to the other panels. 2 means
  # twice as tall as the other panels. Only relevant if `expandFocusedSidePanel` is true.
  expandedSidePanelWeight: 2

  # Sometimes the main window is split in two (e.g. when the selected file has both staged and unstaged changes). This setting controls how the two sections are split.
  # Options are:
  # - 'horizontal': split the window horizontally
  # - 'vertical': split the window vertically
  # - 'flexible': (default) split the window horizontally if the window is wide enough, otherwise split vertically
  mainPanelSplitMode: flexible

  # How the window is split when in half screen mode (i.e. after hitting '+' once).
  # Possible values:
  # - 'left': split the window horizontally (side panel on the left, main view on the right)
  # - 'top': split the window vertically (side panel on top, main view below)
  enlargedSideViewLocation: left

  # If true, wrap lines in the staging view to the width of the view. This
  # makes it much easier to work with diffs that have long lines, e.g.
  # paragraphs of markdown text.
  wrapLinesInStagingView: true

  # One of 'auto' (default) | 'en' | 'zh-CN' | 'zh-TW' | 'pl' | 'nl' | 'ja' | 'ko' | 'ru'
  language: auto

  # Format used when displaying time e.g. commit time.
  # Uses Go's time format syntax: https://pkg.go.dev/time#Time.Format
  timeFormat: 02 Jan 06

  # Format used when displaying time if the time is less than 24 hours ago.
  # Uses Go's time format syntax: https://pkg.go.dev/time#Time.Format
  shortTimeFormat: 3:04PM


  # ---------------------------------------------------------------------------
  # Theme

  # Config relating to colors and styles.
  # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#color-attributes
  theme:
    # Border color of focused window
    activeBorderColor:
      - "#569CD6"
      - bold

    # Border color of non-focused windows
    inactiveBorderColor:
      - "#606366"

    # Border color of focused window when searching in that window
    searchingActiveBorderColor:
      - "#FF0000"
      # - cyan
      - bold

    # Color of keybindings help text in the bottom line
    optionsTextColor:
      - "#569CD6"

    # Background color of selected line.
    # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#highlighting-the-selected-line
    selectedLineBgColor:
      - "#252525"

    # Background color of selected line when view doesn't have focus.
    inactiveViewSelectedLineBgColor:
      - "#252525"

    # Foreground color of copied commit
    cherryPickedCommitFgColor:
      - "#569CD6"
      # - "#FF0000"
      # - blue

    # Background color of copied commit
    cherryPickedCommitBgColor:
      - "#569CD6"
      - "#FF0000"
      # - cyan

    # Foreground color of marked base commit (for rebase)
    markedBaseCommitFgColor:
      - "#45C8B0"

    # Background color of marked base commit (for rebase)
    markedBaseCommitBgColor:
      - "#E8BF6A"

    # Color for file with unstaged changes
    unstagedChangesColor:
      - "#FF0000"

    # Default text color
    defaultFgColor:
      - "#ABABAB"


  # ---------------------------------------------------------------------------
  # Old stuff below:


# Specify a command to be executed
# like `/bin/bash -l`, `ls`, or any other commands
# the default is bash for Linux
# or powershell.exe for Windows
command: echo "YOU NEED TO SPECIFY YOUR OWN COMMAND WITH THE -d ARG"

# Specify the current working directory path
# the default is the current working directory path
cwd: null

# Export additional ENV variables
env:
  recording: true

# Explicitly set the number of columns
# or use `auto` to take the current
# number of columns of your shell
cols: 120 # 100

# Explicitly set the number of rows
# or use `auto` to take the current
# number of rows of your shell
rows: 35 # 30

# Amount of times to repeat GIF
# If value is -1, play once
# If value is 0, loop indefinitely
# If value is a positive number, loop n times
repeat: 0

# Quality
# 1 - 100
# Higher quality seems to make no difference, but running it through
# gifsicle ends up with a much better compressed version.
quality: 100

# Delay between frames in ms
# If the value is `auto` use the actual recording delays
frameDelay: auto

# Maximum delay between frames in ms
# Ignored if the `frameDelay` isn't set to `auto`
# Set to `auto` to prevent limiting the max idle time
maxIdleTime: 2000

# The surrounding frame box
# The `type` can be null, window, floating, or solid`
# To hide the title use the value null
# Don't forget to add a backgroundColor style with a null as type
frameBox:
  type: floating
  title: Lazygit
  style:
    border: 0px black solid
    backgroundColor: "#191B1C"
    margin: -5px

# Add a watermark image to the rendered gif
# You need to specify an absolute path for
# the image on your machine or a URL, and you can also
# add your own CSS styles
watermark:
  imagePath: null
  style:
    position: absolute
    right: 15px
    bottom: 15px
    width: 100px
    opacity: 0.9

# Cursor style can be one of
# `block`, `underline`, or `bar`
cursorStyle: block

# Font family
# You can use any font that is installed on your machine
# in CSS-like syntax
# Download from:
# https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/DejaVuSansMono.zip
# Not using the mono font because it makes icons too small.
fontFamily: "MesloLGMDZ Nerd Font Mono Regular"

# The size of the font
fontSize: 8

# The height of lines
lineHeight: 1

# The spacing between letters
letterSpacing: 0


# -----------------------------------------------------------------------------
# MannyDark Color Palette

# black      = #191B1C
# blue       = #569CD6
# blueLink   = #287BDE
# gray       = #606366
# grayDark   = #252525
# green      = #4FA544
# greenLight = #A5C25C
# orange     = #E8BF6A
# orangeDark = #3E372A
# pink       = #ED3276
# purple     = #C064C7
# red        = #FF0000
# redDark    = #553939
# redLight   = #CE9178
# turquoise  = #45C8B0
# white      = #ABABAB
# yellow     = #DCDCAA
