#!/usr/bin/env sh

#------------------------------------------------------------------------------
# SketchyBar Configuration File
#------------------------------------------------------------------------------

# $CONFIG_DIR is the absolute path to SketchyBar's configuration directory:
# $HOME/.config/sketchybar/

# Make color palette available for this file:
source "$CONFIG_DIR/color_palette.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"


#------------------------------------------------------------------------------
# Settings

PADDING=3

sketchybar --bar position=bottom \
                 height=15 \
                 blur_radius=100 \
                 color=0xff000000 \
                 corner_radius=0 \
                 padding_left=0 \
                 padding_right=0 \
                 notch_width=0 \
                 notch_offset=0 \
                 display=all \
                 topmost=window

defaults=(
  icon.color=$WHITE
  icon.font="MesloLGMDZ Nerd Font Mono:Bold:12.0"
  label.color=$WHITE
  label.font="MesloLGMDZ Nerd Font Mono:Bold:12.0"
  ignore_association=on
)
sketchybar --default "${defaults[@]}"


#------------------------------------------------------------------------------
# Yabai WM Setup
# ACTIVE="$(yabai -m query --displays --display | jq ".index")"


#------------------------------------------------------------------------------
#----- Left Items

source "$ITEM_DIR/aerospace.sh"
# source "$ITEM_DIR/space.sh" (Yabai WM)


#------------------------------------------------------------------------------
# Right Items

source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/separator.sh" "separator_1"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/separator.sh" "separator_2"
source "$ITEM_DIR/input_locale.sh"
source "$ITEM_DIR/separator.sh" "separator_3"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/separator.sh" "separator_4"
source "$ITEM_DIR/memory.sh"
source "$ITEM_DIR/separator.sh" "separator_5"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/separator.sh" "separator_6"
source "$ITEM_DIR/public_ip.sh"
source "$ITEM_DIR/separator.sh" "separator_7"
source "$ITEM_DIR/ethernet.sh"
source "$ITEM_DIR/separator.sh" "separator_8"
source "$ITEM_DIR/wifi.sh"


#------------------------------------------------------------------------------
# SketchyBar Start Up

# Force all scripts to run the first time (never do this in a script):
sketchybar --update

